# Generated by Django 6.0.3 on 2026-04-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
